# Form implementation generated from reading ui file 'prfrence_menue.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_prefrence_menu(object):
    def setupUi(self, prefrence_menu):
        prefrence_menu.setObjectName("prefrence_menu")
        prefrence_menu.resize(708, 367)
        self.horizontalLayout = QtWidgets.QHBoxLayout(prefrence_menu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=prefrence_menu)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(prefrence_menu)
        QtCore.QMetaObject.connectSlotsByName(prefrence_menu)

    def retranslateUi(self, prefrence_menu):
        _translate = QtCore.QCoreApplication.translate
        prefrence_menu.setWindowTitle(_translate("prefrence_menu", "Dialog"))
        self.pushButton_3.setText(_translate("prefrence_menu", "Interviews "))
        self.pushButton_2.setText(_translate("prefrence_menu", "Mentor Meeting"))
        self.pushButton.setText(_translate("prefrence_menu", "Menu Applications"))
