# Form implementation generated from reading ui file 'prfrence_menue.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_prefrence_menu(object):
    def setupUi(self, prefrence_menu):
        prefrence_menu.setObjectName("prefrence_menu")
        prefrence_menu.resize(559, 464)
        prefrence_menu.setAutoFillBackground(True)
        self.label = QtWidgets.QLabel(parent=prefrence_menu)
        self.label.setGeometry(QtCore.QRect(140, 120, 201, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../Downloads/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=prefrence_menu)
        self.widget.setGeometry(QtCore.QRect(150, 250, 191, 151))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 0, 1, 1)

        self.retranslateUi(prefrence_menu)
        QtCore.QMetaObject.connectSlotsByName(prefrence_menu)

    def retranslateUi(self, prefrence_menu):
        _translate = QtCore.QCoreApplication.translate
        prefrence_menu.setWindowTitle(_translate("prefrence_menu", "Dialog"))
        self.pushButton.setText(_translate("prefrence_menu", "Menu Applications"))
        self.pushButton_3.setText(_translate("prefrence_menu", "Interviews "))
        self.pushButton_2.setText(_translate("prefrence_menu", "Mentor Meeting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    prefrence_menu = QtWidgets.QDialog()
    ui = Ui_prefrence_menu()
    ui.setupUi(prefrence_menu)
    prefrence_menu.show()
    sys.exit(app.exec())