# Form implementation generated from reading ui file 'Application.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from pathlib import Path

#sys.path
sys.path.append(str(Path(__file__).parent.parent))

#recall the function from  backend
from backend.list_files import list_files
from backend.set_table_data import set_table_data

class Ui_applications(object):
    def setupUi(self, applications):
        applications.setObjectName("applications")
        applications.resize(1006, 490)
        applications.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(170, 170, 170);")
        self.centralwidget = QtWidgets.QWidget(parent=applications)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 0, 461, 121))
        self.label.setStyleSheet("background-color: rgb(165, 170, 169);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/eng.alahdal/Downloads/logo-1.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(640, 10, 521, 91))
        self.label_2.setMinimumSize(QtCore.QSize(521, 91))
        self.label_2.setStyleSheet("font: 700 20pt \"Times New Roman\";\n"
"color: rgb(81, 81, 81);")
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(170, 130, 811, 301))
        self.tableWidget.setStyleSheet("background-color: rgb(170, 170, 170);")
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(150)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 151, 111))
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/eng.alahdal/Downloads/aa.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 130, 150, 312))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.lineEdit.setStyleSheet("background-color: rgb(231, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_11.setStyleSheet("font: 700 8pt \"Times New Roman\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_10.setStyleSheet("font: 700 8pt \"Times New Roman\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.layoutWidget.raise_()
        self.tableWidget.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        applications.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=applications)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 21))
        self.menubar.setObjectName("menubar")
        applications.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=applications)
        self.statusbar.setObjectName("statusbar")
        applications.setStatusBar(self.statusbar)

        self.retranslateUi(applications)
        QtCore.QMetaObject.connectSlotsByName(applications)
        self.lineEdit.textChanged.connect(self.search_action)
    
    def retranslateUi(self, applications):
        _translate = QtCore.QCoreApplication.translate
        applications.setWindowTitle(_translate("applications", "Applications"))
        self.label_2.setText(_translate("applications", "PROJECT APPLICATIONS"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("applications", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("applications", "Name Sure Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("applications", "Mail"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("applications", "Telephone"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("applications", "Post code"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("applications", "State"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("applications", "Status"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("applications", " Economical Situatie "))
        self.pushButton.setText(_translate("applications", "Search"))
        self.pushButton_2.setText(_translate("applications", "All Applicatios"))
        self.pushButton_11.setText(_translate("applications", "Planned Mentor Meeting"))
        self.pushButton_10.setText(_translate("applications", "Unsecheduled M. Meeting"))
        self.pushButton_9.setText(_translate("applications", "Previous VIT Control"))
        self.pushButton_8.setText(_translate("applications", "Repeated Registrations"))
        self.pushButton_7.setText(_translate("applications", "Different Registrations"))
        self.pushButton_6.setText(_translate("applications", "Filter Application"))
        self.pushButton_5.setText(_translate("applications", "Back Menue"))
        self.pushButton_4.setText(_translate("applications", "Exit"))

    def search_action(self):
        search_text = self.lineEdit.text()
        print(f"🔍  search :  {search_text}")
    
        for row in range(self.tableWidget.rowCount()):
           item = self.tableWidget.item(row, 2)
           match = search_text.lower() in item.text().lower() if item else False
           self.tableWidget.setRowHidden(row, not match)


def application():
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    application = Ui_applications()
    # Set the table data from the Excel file
    application.setupUi(main_window)
# Set the table data from the Excel file
    if application.tableWidget is None:
       print("Table widget is not initialized.")
    else:
        print("Table widget is initialized.")
        application.tableWidget.setColumnCount(0)
        application.tableWidget.setRowCount(0)
    # Set the table data from the Excel file
        set_table_data(application, "Applications.xlsx")

    set_table_data(application, "Applications.xlsx")
    
    main_window.show()
    sys.exit(app.exec())

if __name__ == "__main__":
   """  import sys
    app = QtWidgets.QApplication(sys.argv)
    applications = QtWidgets.QMainWindow()
    ui = Ui_applications()
    ui.setupUi(applications)
    applications.show()
    sys.exit(app.exec()) """
   application()
