""" # Form implementation generated from reading ui file 'PreferencesAdmin.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets,uic
import os

class Ui_PrefernceAdmin(object):
    def setupUi(self, PrefernceAdmin):
        PrefernceAdmin.setObjectName("PrefernceAdmin")
        PrefernceAdmin.resize(470, 284)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        PrefernceAdmin.setFont(font)
        PrefernceAdmin.setStyleSheet("background-color: rgb(165, 170, 169);\n"
"font: 700 10pt \"Times New Roman\";")
        self.centralwidget = QtWidgets.QWidget(parent=PrefernceAdmin)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(189, 189, 189);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(189, 189, 189);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 10, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777214, 10000))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/eng.alahdal/Downloads/logo-1.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 2)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(189, 189, 189);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 11, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(189, 189, 189);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 6, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(189, 189, 189);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 10, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(189, 189, 189);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 11, 0, 1, 1)
        PrefernceAdmin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=PrefernceAdmin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 21))
        self.menubar.setObjectName("menubar")
        PrefernceAdmin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=PrefernceAdmin)
        self.statusbar.setObjectName("statusbar")
        PrefernceAdmin.setStatusBar(self.statusbar)

        self.retranslateUi(PrefernceAdmin)
        QtCore.QMetaObject.connectSlotsByName(PrefernceAdmin)

        self.pushButton.clicked.connect(self.open_applications_form)
        self.pushButton_3.clicked.connect(self.open_admin_form)
        self.pushButton_6.clicked.connect(QtWidgets.QApplication.quit)
        self.pushButton_4.clicked.connect(self.open_mentor_interview_form)
        self.pushButton_2.clicked.connect(self.open_interviews_form)
        self.pushButton_5.clicked.connect(self.open_main_menu_form)
    def retranslateUi(self, PrefernceAdmin):
        _translate = QtCore.QCoreApplication.translate
        PrefernceAdmin.setWindowTitle(_translate("PrefernceAdmin", "Admin Preference Menue"))
        self.pushButton.setText(_translate("PrefernceAdmin", "Applications"))
        self.pushButton_3.setText(_translate("PrefernceAdmin", "Admin "))
        self.pushButton_6.setText(_translate("PrefernceAdmin", "Exit"))
        self.pushButton_4.setText(_translate("PrefernceAdmin", "Mentor Interview"))
        self.pushButton_2.setText(_translate("PrefernceAdmin", "Interview"))
        self.pushButton_5.setText(_translate("PrefernceAdmin", "Main Menue"))
    def open_applications_form(self):
     try:
        self.applications_window = uic.loadUi("Application.ui")
        self.admin_window.show()
        self.applications_window.show()
     except Exception as e:
        print(f"wrong open the form {e}")

    def open_admin_form(self):
        try:
            #self.admin_window = uic.loadUi("AdminMenue.ui")
            ui_file = os.path.join(os.path.dirname(__file__), "AdminMenue.ui")
            self.admin_window = uic.loadUi(ui_file)
            self.admin_window.setWindowTitle(f"Admin Dashboard - {self.applications_window.windowTitle()}")
            self.admin_window.show()
           # QtWidgets.QApplication.instance().activeWindow().close()
        except  Exception as e:
            print(f"wrong open the form {e}")

    def open_mentor_interview_form(self):
        try:
        #     self.mentor_interview_window = uic.loadUi("MentorMenu.ui")
        #     self.mentor_interview_window.show()
            ui_file = os.path.join(os.path.dirname(__file__), "MentorMenu.ui")
            self.mentor_interview_window = uic.loadUi(ui_file)
            self.mentor_interview_window.setWindowTitle(f"Mentor Menue - {self.applications_window.windowTitle()}")
            self.mentor_interview_window.show()
        except Exception as e:
            print(f"wrong open the form {e}")

    def open_interviews_form(self):
        try:
            self.interviews_window = uic.loadUi("Interview.ui")
            self.interviews_window.show()
        except Exception as e:
            print(f"wrong open the form {e}")

    def open_main_menu_form(self):
        try:
            #self.main_menu_window = uic.loadUi("PreferencesAdmin.ui")
            ui_file = os.path.join(os.path.dirname(__file__), "PreferencesAdmin.ui")
            self.admin_window = uic.loadUi(ui_file)
            self.admin_window.setWindowTitle(f"Admin Main - {self.applications_window.windowTitle()}")
            self.admin_window.show()
           # self.main_menu_window.show()
        except Exception as e:
            print(f"wrong open the form {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PrefernceAdmin = QtWidgets.QMainWindow()
    ui = Ui_PrefernceAdmin()
    ui.setupUi(PrefernceAdmin)
    PrefernceAdmin.show()
    sys.exit(app.exec())
 """
from PyQt6 import QtCore, QtGui, QtWidgets, uic
import os
import sys
from pathlib import Path
#from PreferencesAdmin import PreferencesAdminWindow 
#sys.path
sys.path.append(str(Path(__file__).parent.parent))

#recall the function from  backend
from backend.list_files import list_files
from backend.set_table_data import set_table_data
# 
from mentormenu import Ui_MentorMenue
from interview import Ui_Interviews
#from main import Ui_MainMenu
from Application import Ui_applications
#from adminmenue import Ui_adminmenue

class PreferencesAdminWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setup_ui()
        self.setup_connections()
        
    def setup_ui(self):
        """Initialize the UI components"""
        self.setObjectName("PrefernceAdmin")
        self.resize(470, 284)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.setFont(font)
        self.setStyleSheet("""
            background-color: rgb(165, 170, 169);
            font: 700 10pt "Times New Roman";
        """)
        
        self.centralwidget = QtWidgets.QWidget()
        self.setCentralWidget(self.centralwidget)
        
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        
        # Create buttons
        self.btn_applications = QtWidgets.QPushButton("Applications")
        self.btn_admin = QtWidgets.QPushButton("Admin")
        self.btn_exit = QtWidgets.QPushButton("Exit")
        self.btn_mentor_interview = QtWidgets.QPushButton("Mentor Interview")
        self.btn_interview = QtWidgets.QPushButton("Interview")
        self.btn_main_menu = QtWidgets.QPushButton("Main Menu")
        
        # Style buttons
        button_style = """
            font: 700 10pt "Times New Roman";
            background-color: rgb(189, 189, 189);
            padding: 5px;
        """
        for btn in [self.btn_applications, self.btn_admin, self.btn_exit, 
                   self.btn_mentor_interview, self.btn_interview, self.btn_main_menu]:
            btn.setStyleSheet(button_style)
        
        # Add logo
        self.logo_label = QtWidgets.QLabel()
        self.logo_label.setMaximumSize(QtCore.QSize(16777214, 10000))
        logo_path = os.path.join(os.path.dirname(__file__), "D:/Python-Module-Week7/ui/logo-1.png")
        #self.logo_label.setPixmap(QtGui.QPixmap(logo_path))
        if os.path.exists(logo_path):
            self.logo_label.setPixmap(QtGui.QPixmap(logo_path))
        
        # Layout organization
        self.gridLayout.addWidget(self.logo_label, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.btn_applications, 1, 0)
        self.gridLayout.addWidget(self.btn_mentor_interview, 1, 1)
        self.gridLayout.addWidget(self.btn_interview, 2, 0)
        self.gridLayout.addWidget(self.btn_admin, 2, 1)
        self.gridLayout.addWidget(self.btn_main_menu, 3, 0)
        self.gridLayout.addWidget(self.btn_exit, 3, 1)
        
        self.setWindowTitle("Admin Preference Menu")
        
    def setup_connections(self):
        """Connect buttons to their respective functions"""
        self.btn_applications.clicked.connect(self.open_applications_form)
        self.btn_admin.clicked.connect(self.open_admin_form)
        self.btn_exit.clicked.connect(self.close_application)
        self.btn_mentor_interview.clicked.connect(self.open_mentor_interview_form)
        self.btn_interview.clicked.connect(self.open_interviews_form)
        self.btn_main_menu.clicked.connect(self.open_main_menu_form)
    
    def load_ui_file(self, ui_filename):
        """Helper method to load UI files with error handling"""
        try:
            ui_path = os.path.join(os.path.dirname(__file__), ui_filename)
            if not os.path.exists(ui_path):
                raise FileNotFoundError(f"UI file not found: {ui_path}")
            return uic.loadUi(ui_path)
        except Exception as e:
            QtWidgets.QMessageBox.critical(
                self, 
                "Error", 
                f"Failed to load {ui_filename}:\n{str(e)}"
            )
            return None
    
    def open_applications_form(self):
        """Open the applications form"""
        self.main_window = QtWidgets.QMainWindow()
        self.application = Ui_applications()
        self.application.setupUi(self.main_window)

        if self.application.tableWidget is None:
          print("Table widget is not initialized.")
        else:
           print("Table widget is initialized.")
           self.application.tableWidget.setColumnCount(0)
           self.application.tableWidget.setRowCount(0)
        set_table_data(self.application, "Applications.xlsx")
        self.main_window.show()
    
    def open_admin_form(self):
        """Open the admin menu form"""
        from adminmenue import Ui_adminmenue  # Move import here
        self.admin_window = QtWidgets.QMainWindow()
        self.admin_ui = Ui_adminmenue()
        self.admin_ui.setupUi(self.admin_window)
        self.admin_window.show()
        # self.preference_window = Ui_adminmenue()
        # self.preference_window.show()
    
    def open_mentor_interview_form(self):
        """Open the mentor interview form"""
        print("🔘 open Mentor Meeting")
  
        self.mentor_ui = Ui_MentorMenue()
        self.main_window = QtWidgets.QMainWindow()
        self.application = Ui_MentorMenue()
        self.application.setupUi(self.main_window)

        if self.application.tableWidget is None:
          print("Table widget is not initialized.")
        else:
           print("Table widget is initialized.")
           self.application.tableWidget.setColumnCount(0)
           self.application.tableWidget.setRowCount(0)
        set_table_data(self.application, "Mentors.xlsx")

        self.main_window.show()
    
    def open_interviews_form(self):
        """Open the interviews form"""
        self.main_window = QtWidgets.QMainWindow()
        self.application = Ui_Interviews()
        self.application.setupUi(self.main_window)

        if self.application.tableWidget is None:
          print("Table widget is not initialized.")
        else:
           print("Table widget is initialized.")
           self.application.tableWidget.setColumnCount(0)
           self.application.tableWidget.setRowCount(0)
        set_table_data(self.application, "Interviews.xlsx")

        self.main_window.show()
    
    def open_main_menu_form(self):
        """Open the main menu form"""
        from login import new_login  # Move import here
        self.user_window = QtWidgets.QMainWindow()
        self.user_ui = new_login()
        self.user_ui.setupUi(self.user_window)
        self.user_window.show()
    
    def close_application(self):
        """Close the application"""
        self.close()
        QtWidgets.QApplication.quit()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    
    # Set application style and font
    app.setStyle("Fusion")
    font = QtGui.QFont("Times New Roman", 10)
    font.setBold(True)
    app.setFont(font)
    
    window = PreferencesAdminWindow()
    window.show()
    sys.exit(app.exec())