# # """ """ # Form implementation generated from reading ui file 'UserLogin.ui'
# # #
# # # Created by: PyQt6 UI code generator 6.9.0
# # #
# # # WARNING: Any manual changes made to this file will be lost when pyuic6 is
# # # run again.  Do not edit this file unless you know what you are doing.

# # from PyQt6 import QtCore, QtGui, QtWidgets


# # class Ui_new_login(object):
# #     def setupUi(self, new_login):
# #         new_login.setObjectName("new_login")
# #         new_login.resize(541, 328)
# #         new_login.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
# # "background-color: rgb(165, 170, 169);")
# #         self.centralwidget = QtWidgets.QWidget(parent=new_login)
# #         self.centralwidget.setObjectName("centralwidget")
# #         self.label = QtWidgets.QLabel(parent=self.centralwidget)
# #         self.label.setGeometry(QtCore.QRect(120, 130, 81, 31))
# #         self.label.setStyleSheet("font: 700 10pt \"Times New Roman\";")
# #         self.label.setObjectName("label")
# #         self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
# #         self.label_2.setGeometry(QtCore.QRect(120, 170, 81, 31))
# #         self.label_2.setStyleSheet("font: 700 10pt \"Times New Roman\";")
# #         self.label_2.setObjectName("label_2")
# #         self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
# #         self.textEdit.setGeometry(QtCore.QRect(190, 130, 181, 31))
# #         self.textEdit.setObjectName("textEdit")
# #         self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
# #         self.textEdit_2.setGeometry(QtCore.QRect(190, 170, 181, 31))
# #         self.textEdit_2.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
# # "color: rgb(0, 0, 0);")
# #         self.textEdit_2.setObjectName("textEdit_2")
# #         self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
# #         self.pushButton.setGeometry(QtCore.QRect(120, 250, 75, 31))
# #         self.pushButton.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
# # "background-color: rgb(207, 255, 253);")
# #         self.pushButton.setObjectName("pushButton")
# #         self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
# #         self.pushButton_2.setGeometry(QtCore.QRect(300, 250, 75, 31))
# #         self.pushButton_2.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
# # "background-color: rgb(207, 255, 253);")
# #         self.pushButton_2.setObjectName("pushButton_2")
# #         self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
# #         self.label_3.setGeometry(QtCore.QRect(60, -5, 481, 111))
# #         self.label_3.setText("")
# #         self.label_3.setPixmap(QtGui.QPixmap("C:/Users/eng.alahdal/Downloads/logo-1.png"))
# #         self.label_3.setObjectName("label_3")
# #         self.errorlabel = QtWidgets.QLabel(parent=self.centralwidget)
# #         self.errorlabel.setGeometry(QtCore.QRect(190, 210, 171, 16))
# #         self.errorlabel.setText("")
# #         self.errorlabel.setStyleSheet("color: red;")
# #         self.errorlabel.setObjectName("errorlabel")
# #         new_login.setCentralWidget(self.centralwidget)
# #         self.statusbar = QtWidgets.QStatusBar(parent=new_login)
# #         self.statusbar.setObjectName("statusbar")
# #         new_login.setStatusBar(self.statusbar)

# #         self.retranslateUi(new_login)
# #         QtCore.QMetaObject.connectSlotsByName(new_login)

# #     def retranslateUi(self, new_login):
# #         _translate = QtCore.QCoreApplication.translate
# #         new_login.setWindowTitle(_translate("new_login", "Login User form"))
# #         self.label.setText(_translate("new_login", "User name"))
# #         self.label_2.setText(_translate("new_login", "Password"))
# #         self.pushButton.setText(_translate("new_login", "Login"))
# #         self.pushButton_2.setText(_translate("new_login", "Exit"))


# # if __name__ == "__main__":
# #     import sys
# #     app = QtWidgets.QApplication(sys.argv)
# #     new_login = QtWidgets.QMainWindow()
# #     ui = Ui_new_login()
# #     ui.setupUi(new_login)
# #     new_login.show()
# #     sys.exit(app.exec())
# #  """
# # from PyQt6 import QtCore, QtGui, QtWidgets
# # from openpyxl import load_workbook

# # class Ui_new_login(object):
# #     def setupUi(self, new_login):
# #         new_login.setObjectName("new_login")
# #         new_login.resize(541, 328)
# #         new_login.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
# # "background-color: rgb(165, 170, 169);")
# #         self.centralwidget = QtWidgets.QWidget(parent=new_login)
# #         self.centralwidget.setObjectName("centralwidget")
# #         self.label = QtWidgets.QLabel(parent=self.centralwidget)
# #         self.label.setGeometry(QtCore.QRect(120, 130, 81, 31))
# #         self.label.setStyleSheet("font: 700 10pt \"Times New Roman\";")
# #         self.label.setObjectName("label")
# #         self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
# #         self.label_2.setGeometry(QtCore.QRect(120, 170, 81, 31))
# #         self.label_2.setStyleSheet("font: 700 10pt \"Times New Roman\";")
# #         self.label_2.setObjectName("label_2")
# #         self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
# #         self.textEdit.setGeometry(QtCore.QRect(190, 130, 181, 31))
# #         self.textEdit.setObjectName("textEdit")
# #         self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
# #         self.textEdit_2.setGeometry(QtCore.QRect(190, 170, 181, 31))
# #         self.textEdit_2.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
# # "color: rgb(0, 0, 0);")
# #         self.textEdit_2.setObjectName("textEdit_2")
# #         self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
# #         self.pushButton.setGeometry(QtCore.QRect(120, 250, 75, 31))
# #         self.pushButton.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
# # "background-color: rgb(207, 255, 253);")
# #         self.pushButton.setObjectName("pushButton")
# #         self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
# #         self.pushButton_2.setGeometry(QtCore.QRect(300, 250, 75, 31))
# #         self.pushButton_2.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
# # "background-color: rgb(207, 255, 253);")
# #         self.pushButton_2.setObjectName("pushButton_2")
# #         self.pushButton_2.clicked.connect(new_login.close)  
# #         # 

# #         self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
# #         self.label_3.setGeometry(QtCore.QRect(60, -5, 481, 111))
# #         self.label_3.setText("")
# #         self.label_3.setPixmap(QtGui.QPixmap("C:/Users/eng.alahdal/Downloads/logo-1.png"))
# #         self.label_3.setObjectName("label_3")
# #         self.errorlabel = QtWidgets.QLabel(parent=self.centralwidget)
# #         self.errorlabel.setGeometry(QtCore.QRect(190, 210, 250, 16))
# #         self.errorlabel.setStyleSheet("color: red;")
# #         self.errorlabel.setText("")
# #         self.errorlabel.setObjectName("errorlabel")
# #         new_login.setCentralWidget(self.centralwidget)
# #         self.statusbar = QtWidgets.QStatusBar(parent=new_login)
# #         self.statusbar.setObjectName("statusbar")
# #         new_login.setStatusBar(self.statusbar)

# #         # ربط زر الدخول بوظيفة التحقق
# #         self.pushButton.clicked.connect(self.check_login)

# #         self.retranslateUi(new_login)
# #         QtCore.QMetaObject.connectSlotsByName(new_login)

# #     def retranslateUi(self, new_login):
# #         _translate = QtCore.QCoreApplication.translate
# #         new_login.setWindowTitle(_translate("new_login", "Login User form"))
# #         self.label.setText(_translate("new_login", "User name"))
# #         self.label_2.setText(_translate("new_login", "Password"))
# #         self.pushButton.setText(_translate("new_login", "Login"))
# #         self.pushButton_2.setText(_translate("new_login", "Exit"))
    
   
# #     def load_users_from_excel(self):
    
# #         try:
# #             wb = load_workbook(filename='users.xlsx')
# #             sheet = wb.active
# #             users = {}
            
# #             # نبدأ من الصف الثاني لأن الصف الأول يحتوي على العناوين
# #             for row in sheet.iter_rows(min_row=2, values_only=True):
# #                 username, password, role = row[0], row[1], row[2]
# #                 users[username] = {"password": password, "role": role.lower()}
            
# #             return users
# #         except FileNotFoundError:
# #             self.errorlabel.setText("ملف المستخدمين (users.xlsx) غير موجود")
# #             return {}
# #         except Exception as e:
# #             self.errorlabel.setText(f"خطأ في قراءة الملف: {str(e)}")
# #             return {}
        

# #     def check_login(self):
# #         username = self.textEdit.toPlainText().strip()
# #         password = self.textEdit_2.toPlainText().strip()

# #         if not username or not password:
# #             self.errorlabel.setText("يرجى إدخال اسم المستخدم وكلمة المرور")
# #             return

# #         users = self.load_users_from_excel()
        
# #         if username in users:
# #             if users[username]["password"] == password:
# #                 role = users[username].get("role", "user")
# #                 self.errorlabel.setStyleSheet("color: green;")
# #                 self.errorlabel.setText(f"مرحباً {username}! جاري التوجيه...")
# #                 QtCore.QTimer.singleShot(1000, lambda: self.open_dashboard(role, username))
# #             else:
# #                 self.errorlabel.setStyleSheet("color: red;")
# #                 self.errorlabel.setText("كلمة المرور غير صحيحة")
# #         else:
# #             self.errorlabel.setStyleSheet("color: red;")
# #             self.errorlabel.setText("اسم المستخدم غير موجود")

        
# #     def open_dashboard(self, role, username):
       
# #         if role == "admin":
# #             self.open_admin_form(username)
# #         else:
# #             self.open_user_form(username)
# # from PyQt6 import uic

# # def open_admin_form(self, username):
# #     """فتح واجهة المدير من ملف UI"""
# #     try:
# #         # تحميل ملف واجهة المدير
# #         self.admin_window = uic.loadUi("adminmenue.ui")
# #         self.admin_window.setWindowTitle(f"Admin Dashboard - {username}")
        
# #         # يمكنك الوصول إلى العناصر هنا مثلاً:
# #         # self.admin_window.labelWelcome.setText(f"مرحباً بك {username} (مدير النظام)")
        
# #         self.admin_window.show()
# #         QtWidgets.QApplication.activeWindow().close()
# #     except Exception as e:
# #         print(f"Error loading admin form: {e}")

# # def open_user_form(self, username):
# #     """فتح واجهة المستخدم من ملف UI"""
# #     try:
# #         # تحميل ملف واجهة المستخدم
# #         self.user_window = uic.loadUi("usermenue.ui")
# #         self.user_window.setWindowTitle(f"User Dashboard - {username}")
        
# #         # يمكنك الوصول إلى العناصر هنا مثلاً:
# #         # self.user_window.labelWelcome.setText(f"مرحباً بك {username} (مستخدم عادي)")
        
# #         self.user_window.show()
# #         QtWidgets.QApplication.activeWindow().close()
# #     except Exception as e:
# #         print(f"Error loading user form: {e}")

# # if __name__ == "__main__":
# #     import sys
# #     app = QtWidgets.QApplication(sys.argv)
# #     new_login = QtWidgets.QMainWindow()
# #     ui = Ui_new_login()
# #     ui.setupUi(new_login)
# #     new_login.show()
# #     sys.exit(app.exec())
# #  """

# from PyQt6 import QtCore, QtGui, QtWidgets, uic
# from openpyxl import load_workbook


# class Ui_new_login(object):
#     def setupUi(self, new_login):
#         self.window = new_login
#         new_login.setObjectName("new_login")
#         new_login.resize(541, 328)
#         new_login.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
#                                 "background-color: rgb(165, 170, 169);")

#         self.centralwidget = QtWidgets.QWidget(parent=new_login)
#         self.centralwidget.setObjectName("centralwidget")

#         self.label = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label.setGeometry(QtCore.QRect(120, 130, 81, 31))
#         self.label.setText("User name")

#         self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label_2.setGeometry(QtCore.QRect(120, 170, 81, 31))
#         self.label_2.setText("Password")

#         self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
#         self.textEdit.setGeometry(QtCore.QRect(190, 130, 181, 31))

#         self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
#         self.textEdit_2.setGeometry(QtCore.QRect(190, 170, 181, 31))

#         self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(120, 250, 75, 31))
#         self.pushButton.setText("Login")

#         self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
#         self.pushButton_2.setGeometry(QtCore.QRect(300, 250, 75, 31))
#         self.pushButton_2.setText("Exit")
#         self.pushButton_2.clicked.connect(new_login.close)

#         self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label_3.setGeometry(QtCore.QRect(60, -5, 481, 111))
#         self.label_3.setPixmap(QtGui.QPixmap("C:/Users/eng.alahdal/Downloads/logo-1.png"))

#         self.errorlabel = QtWidgets.QLabel(parent=self.centralwidget)
#         self.errorlabel.setGeometry(QtCore.QRect(190, 210, 250, 16))
#         self.errorlabel.setStyleSheet("color: red;")
#         self.errorlabel.setText("")

#         new_login.setCentralWidget(self.centralwidget)

#         self.statusbar = QtWidgets.QStatusBar(parent=new_login)
#         new_login.setStatusBar(self.statusbar)

#         self.pushButton.clicked.connect(self.check_login)

#         self.retranslateUi(new_login)
#         QtCore.QMetaObject.connectSlotsByName(new_login)

#     def retranslateUi(self, new_login):
#         _translate = QtCore.QCoreApplication.translate
#         new_login.setWindowTitle(_translate("new_login", "Login User form"))

#     """ def load_users_from_excel(self):
#         try:
#             wb = load_workbook(filename='Users.xlsx')
#             sheet = wb.active
#             users = {}
#             for row in sheet.iter_rows(min_row=2, values_only=True):
#                 if row[0] and row[1]:
#                     username = str(row[0]).strip()
#                     password = str(row[1]).strip()
#                     role = str(row[2]).strip().lower() if row[2] else "user"
#                     users[username] = {"password": password, "role": role}
#             return users
#         except FileNotFoundError:
#             self.errorlabel.setText("ملف Users.xlsx غير موجود")
#             return {}
#         except Exception as e:
#             self.errorlabel.setText(f"خطأ في قراءة الملف: {str(e)}")
#             return {}

#     def check_login(self):
#         username = self.textEdit.toPlainText().strip()
#         password = self.textEdit_2.toPlainText().strip()

#         if not username or not password:
#             self.errorlabel.setText("يرجى إدخال اسم المستخدم وكلمة المرور")
#             return

#         users = self.load_users_from_excel()
#         if username in users:
#             if users[username]["password"] == password:
#                 role = users[username]["role"]
#                 self.errorlabel.setStyleSheet("color: green;")
#                 self.errorlabel.setText(f"مرحباً {username}! جاري التوجيه...")
#                 QtCore.QTimer.singleShot(1000, lambda: self.open_dashboard(role, username))
#             else:
#                 self.errorlabel.setStyleSheet("color: red;")
#                 self.errorlabel.setText("كلمة المرور غير صحيحة")
#         else:
#             self.errorlabel.setStyleSheet("color: red;")
#             self.errorlabel.setText("اسم المستخدم غير موجود")

#     def open_dashboard(self, role, username):
#         if role == "admin":
#             self.open_admin_form(username)
#         else:
#             self.open_user_form(username)

#     def open_admin_form(self, username):
#         try:
#             self.admin_window = uic.loadUi("AdminMenue.ui")
#             self.admin_window.setWindowTitle(f"Admin Dashboard - {username}")
#             self.admin_window.show()
#             self.window.close()
#         except Exception as e:
#             self.errorlabel.setStyleSheet("color: red;")
#             self.errorlabel.setText(f"خطأ في فتح لوحة المدير: {str(e)}")

#     def open_user_form(self, username):
#         try:
#             self.user_window = uic.loadUi("UserMenue.ui")
#             self.user_window.setWindowTitle(f"User Dashboard - {username}")
#             self.user_window.show()
#             self.window.close()
#         except Exception as e:
#             self.errorlabel.setStyleSheet("color: red;")
#             self.errorlabel.setText(f"خطأ في فتح لوحة المستخدم: {str(e)}")


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     login_window = QtWidgets.QMainWindow()
#     ui = Ui_new_login()
#     ui.setupUi(login_window)
#     login_window.show()
#     sys.exit(app.exec())
#  """
# from PyQt6 import QtCore, QtGui, QtWidgets, uic
# from openpyxl import load_workbook


# class Ui_new_login(object):
#     def setupUi(self, new_login):
#         self.window = new_login
#         new_login.setObjectName("new_login")
#         new_login.resize(541, 328)
#         new_login.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
#                                 "background-color: rgb(165, 170, 169);")

#         self.centralwidget = QtWidgets.QWidget(parent=new_login)
#         self.centralwidget.setObjectName("centralwidget")

#         self.label = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label.setGeometry(QtCore.QRect(120, 130, 81, 31))
#         self.label.setText("User name")

#         self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label_2.setGeometry(QtCore.QRect(120, 170, 81, 31))
#         self.label_2.setText("Password")

#         self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
#         self.textEdit.setGeometry(QtCore.QRect(190, 130, 181, 31))

#         self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
#         self.textEdit_2.setGeometry(QtCore.QRect(190, 170, 181, 31))

#         self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(120, 250, 75, 31))
#         self.pushButton.setText("Login")

#         self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
#         self.pushButton_2.setGeometry(QtCore.QRect(300, 250, 75, 31))
#         self.pushButton_2.setText("Exit")
#         self.pushButton_2.clicked.connect(new_login.close)

#         self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label_3.setGeometry(QtCore.QRect(60, -5, 481, 111))
#         self.label_3.setPixmap(QtGui.QPixmap("C:/Users/eng.alahdal/Downloads/logo-1.png"))

#         self.errorlabel = QtWidgets.QLabel(parent=self.centralwidget)
#         self.errorlabel.setGeometry(QtCore.QRect(190, 210, 250, 16))
#         self.errorlabel.setStyleSheet("color: red;")
#         self.errorlabel.setText("")

#         new_login.setCentralWidget(self.centralwidget)

#         self.statusbar = QtWidgets.QStatusBar(parent=new_login)
#         new_login.setStatusBar(self.statusbar)

#         self.pushButton.clicked.connect(self.check_login)

#         self.retranslateUi(new_login)
#         QtCore.QMetaObject.connectSlotsByName(new_login)

#     def retranslateUi(self, new_login):
#         _translate = QtCore.QCoreApplication.translate
#         new_login.setWindowTitle(_translate("new_login", "Login User form"))

#     def load_users_from_excel(self):
#         try:
#             wb = load_workbook(filename='Users.xlsx')
#             sheet = wb.active
#             users = {}
#             for row in sheet.iter_rows(min_row=2, values_only=True):
#                 if row[0] and row[1]:
#                     username = str(row[0]).strip()
#                     password = str(row[1]).strip()
#                     role = str(row[2]).strip().lower() if row[2] else "user"
#                     users[username] = {"password": password, "role": role}
#             return users
#         except FileNotFoundError:
#             self.errorlabel.setText("\u0645\u0644\u0641 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645\u064a\u0646 (Users.xlsx) \u063a\u064a\u0631 \u0645\u0648\u062c\u0648\u062f")
#             return {}
#         except Exception as e:
#             self.errorlabel.setText(f"\u062e\u0637\u0623 \u0641\u064a \u0642\u0631\u0627\u0621\u0629 \u0627\u0644\u0645\u0644\u0641: {str(e)}")
#             return {}

#     def check_login(self):
#         username = self.textEdit.toPlainText().strip()
#         password = self.textEdit_2.toPlainText().strip()

#         if not username or not password:
#             self.errorlabel.setText("\u064a\u0631\u062c\u0649 \u0625\u062f\u062e\u0627\u0644 \u0627\u0633\u0645 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645 \u0648\u0643\u0644\u0645\u0629 \u0627\u0644\u0645\u0631\u0648\u0631")
#             return

#         users = self.load_users_from_excel()

#         if username in users:
#             if users[username]["password"] == password:
#                 role = users[username].get("role", "user")
#                 self.errorlabel.setStyleSheet("color: green;")
#                 self.errorlabel.setText(f"\u0645\u0631\u062d\u0628\u0627\u064b {username}! \u062c\u0627\u0631\u064a \u0627\u0644\u062a\u0648\u062c\u064a\u0647...")
#                 QtCore.QTimer.singleShot(1000, lambda: self.open_dashboard(role, username))
#             else:
#                 self.errorlabel.setStyleSheet("color: red;")
#                 self.errorlabel.setText("\u0643\u0644\u0645\u0629 \u0627\u0644\u0645\u0631\u0648\u0631 \u063a\u064a\u0631 \u0635\u062d\u064a\u062d\u0629")
#         else:
#             self.errorlabel.setStyleSheet("color: red;")
#             self.errorlabel.setText("\u0627\u0633\u0645 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645 \u063a\u064a\u0631 \u0645\u0648\u062c\u0648\u062f")

#     def open_dashboard(self, role, username):
#         if role == "admin":
#             self.open_admin_form(username)
#         else:
#             self.open_user_form(username)

#     def open_admin_form(self, username):
#         try:
#             self.admin_window = uic.loadUi("AdminMenue.ui")
#             self.admin_window.setWindowTitle(f"Admin Dashboard - {username}")
#             self.admin_window.show()
#             self.window.close()
#         except Exception as e:
#             print(f"Error loading admin form: {e}")

#     def open_user_form(self, username):
#         try:
#             self.user_window = uic.loadUi("UserMenue.ui")
#             self.user_window.setWindowTitle(f"User Dashboard - {username}")
#             self.user_window.show()
#             self.window.close()
#         except Exception as e:
#             print(f"Error loading user form: {e}")


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     new_login = QtWidgets.QMainWindow()
#     ui = Ui_new_login()
#     ui.setupUi(new_login)
#     new_login.show()
#     sys.exit(app.exec())
from PyQt6 import QtCore, QtGui, QtWidgets, uic
from openpyxl import load_workbook


class Ui_new_login(object):
    def setupUi(self, new_login):
        self.window = new_login
        new_login.setObjectName("new_login")
        new_login.resize(541, 328)
        new_login.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
                                "background-color: rgb(165, 170, 169);")

        self.centralwidget = QtWidgets.QWidget(parent=new_login)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 130, 81, 31))
        self.label.setText("User name")

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 170, 81, 31))
        self.label_2.setText("Password")

        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(190, 130, 181, 31))

        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(190, 170, 181, 31))

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 250, 75, 31))
        self.pushButton.setText("Login")

        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 250, 75, 31))
        self.pushButton_2.setText("Exit")
        self.pushButton_2.clicked.connect(new_login.close)

        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, -5, 481, 111))
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/eng.alahdal/Downloads/logo-1.png"))

        self.errorlabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.errorlabel.setGeometry(QtCore.QRect(190, 210, 250, 16))
        self.errorlabel.setStyleSheet("color: red;")
        self.errorlabel.setText("")

        new_login.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(parent=new_login)
        new_login.setStatusBar(self.statusbar)

        self.pushButton.clicked.connect(self.check_login)

        self.retranslateUi(new_login)
        QtCore.QMetaObject.connectSlotsByName(new_login)

    def retranslateUi(self, new_login):
        _translate = QtCore.QCoreApplication.translate
        new_login.setWindowTitle(_translate("new_login", "Login User form"))

    def load_users_from_excel(self):
        try:
            wb = load_workbook(filename='Users.xlsx')
            sheet = wb.active
            users = {}
            for row in sheet.iter_rows(min_row=2, values_only=True):
                if row[0] and row[1]:
                    username = str(row[0]).strip()
                    password = str(row[1]).strip()
                    role = str(row[2]).strip().lower() if row[2] else "user"
                    users[username] = {"password": password, "role": role}
            return users
        except FileNotFoundError:
            self.errorlabel.setText("\u0645\u0644\u0641 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645\u064a\u0646 (Users.xlsx) \u063a\u064a\u0631 \u0645\u0648\u062c\u0648\u062f")
            return {}
        except Exception as e:
            self.errorlabel.setText(f"\u062e\u0637\u0623 \u0641\u064a \u0642\u0631\u0627\u0621\u0629 \u0627\u0644\u0645\u0644\u0641: {str(e)}")
            return {}

    def check_login(self):
        username = self.textEdit.toPlainText().strip()
        password = self.textEdit_2.toPlainText().strip()

        if not username or not password:
            self.errorlabel.setText("\u064a\u0631\u062c\u0649 \u0625\u062f\u062e\u0627\u0644 \u0627\u0633\u0645 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645 \u0648\u0643\u0644\u0645\u0629 \u0627\u0644\u0645\u0631\u0648\u0631")
            return

        users = self.load_users_from_excel()

        if username in users:
            if users[username]["password"] == password:
                role = users[username].get("role", "user")
                self.errorlabel.setStyleSheet("color: green;")
                self.errorlabel.setText(f"\u0645\u0631\u062d\u0628\u0627\u064b {username}! \u062c\u0627\u0631\u064a \u0627\u0644\u062a\u0648\u062c\u064a\u0647...")
                QtCore.QTimer.singleShot(1000, lambda: self.open_dashboard(role, username))
            else:
                self.errorlabel.setStyleSheet("color: red;")
                self.errorlabel.setText("\u0643\u0644\u0645\u0629 \u0627\u0644\u0645\u0631\u0648\u0631 \u063a\u064a\u0631 \u0635\u062d\u064a\u062d\u0629")
        else:
            self.errorlabel.setStyleSheet("color: red;")
            self.errorlabel.setText("\u0627\u0633\u0645 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645 \u063a\u064a\u0631 \u0645\u0648\u062c\u0648\u062f")

    def open_dashboard(self, role, username):
        if role == "admin":
            self.open_admin_form(username)
        else:
            self.open_user_form(username)

    def open_admin_form(self, username):
        try:
            #self.admin_window = uic.loadUi("adminmenue.ui")
            self.admin_window = uic.loadUi("AdminMenue.ui")
            self.admin_window.setWindowTitle(f"Admin Dashboard - {username}")
            self.admin_window.show()
            self.window.close()
        except Exception as e:
            print(f"Error loading admin form: {e}")

    def open_user_form(self, username):
        try:
            self.user_window = uic.loadUi("UserMenue.ui")
            self.user_window.setWindowTitle(f"User Dashboard - {username}")
            self.user_window.show()
            self.window.close()
        except Exception as e:
            print(f"Error loading user form: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_login = QtWidgets.QMainWindow()
    ui = Ui_new_login()
    ui.setupUi(new_login)
    new_login.show()
    sys.exit(app.exec())
