""" # Form implementation generated from reading ui file 'UserMenue.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_usermenue(object):
    def setupUi(self, usermenue):
        usermenue.setObjectName("usermenue")
        usermenue.resize(469, 285)
        usermenue.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(165, 170, 169);")
        self.centralwidget = QtWidgets.QWidget(parent=usermenue)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(239, 142, 223, 23))
        self.pushButton_4.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(189, 189, 189);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 220, 223, 23))
        self.pushButton_5.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(189, 189, 189);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(240, 220, 223, 23))
        self.pushButton_6.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(189, 189, 189);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 180, 223, 23))
        self.pushButton_2.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(189, 189, 189);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 142, 223, 23))
        self.pushButton.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
"background-color: rgb(189, 189, 189);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 452, 136))
        self.label.setMaximumSize(QtCore.QSize(16777214, 10000))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/eng.alahdal/Downloads/logo-1.png"))
        self.label.setObjectName("label")
        usermenue.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=usermenue)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 469, 21))
        self.menubar.setObjectName("menubar")
        usermenue.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=usermenue)
        self.statusbar.setObjectName("statusbar")
        usermenue.setStatusBar(self.statusbar)

        self.retranslateUi(usermenue)
        QtCore.QMetaObject.connectSlotsByName(usermenue)
       # self.lineEdit.textChanged.connect(self.search_action)# connect text change to search action
        self.pushButton_4.clicked.connect(self.Applictions_action)
        self.pushButton_5.clicked.connect(self.Main_Menue_action)
        self.pushButton_2.clicked.connect(self.Interviews_action)
        self.pushButton.clicked.connect(self.Mentor_Meeting_action)
        self.pushButton_6.clicked.connect(self.exit_app)

    def retranslateUi(self, usermenue):
        _translate = QtCore.QCoreApplication.translate
        usermenue.setWindowTitle(_translate("usermenue", "User Menue"))
        self.pushButton_4.setText(_translate("usermenue", "Applictions"))
        self.pushButton_5.setText(_translate("usermenue", "Main Menue"))
        self.pushButton_6.setText(_translate("usermenue", "Exit"))
        self.pushButton_2.setText(_translate("usermenue", "Interviews"))
        self.pushButton.setText(_translate("usermenue", "Mentor Meeting"))
        def Applications_action(self):
            print("  Applications")
            QtWidgets.QMessageBox.information(None, "Applications", "")
            app = QtWidgets.QApplication(sys.argv)
            mentor_window = QtWidgets.QMainWindow()
            ui = Ui_MentorMenue()
            ui.setupUi(mentor_window)
            mentor_window.show()

        def Main_Menue_action(self):
            print("  Main Menue")
            QtWidgets.QMessageBox.information(None, "Main Menue", "")
        def Interviews_action(self):
            print("  Interviews")
            QtWidgets.QMessageBox.information(None, "Interviews", "")
        def Mentor_Meeting_action(self):
            print("  Mentor Meeting")
            QtWidgets.QMessageBox.information(None, "Mentor Meeting", "")
        def exit_app(self):
            print("  Exit")
            QtWidgets.QMessageBox.information(None, "Exit", "")
            QtWidgets.QApplication.quit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    usermenue = QtWidgets.QMainWindow()
    ui = Ui_usermenue()
    ui.setupUi(usermenue)
    usermenue.show()
    sys.exit(app.exec())
 """

from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from pathlib import Path

#sys.path
sys.path.append(str(Path(__file__).parent.parent))

#recall the function from  backend
from backend.list_files import list_files
from backend.set_table_data import set_table_data
# 
from mentormenu import Ui_MentorMenue
from interview import Ui_Interviews
#from main import Ui_MainMenu
from Application import Ui_applications

class Ui_usermenue(object):
    def setupUi(self, usermenue):
        usermenue.setObjectName("usermenue")
        usermenue.resize(469, 285)
        usermenue.setStyleSheet("font: 700 10pt \"Times New Roman\";\n"
                                "background-color: rgb(165, 170, 169);")
        self.centralwidget = QtWidgets.QWidget(parent=usermenue)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(239, 142, 223, 23))
        self.pushButton_4.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 220, 223, 23))
        self.pushButton_5.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(240, 220, 223, 23))
        self.pushButton_6.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.pushButton_6.setObjectName("pushButton_6")

        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 180, 223, 23))
        self.pushButton_2.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 142, 223, 23))
        self.pushButton.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.pushButton.setObjectName("pushButton")

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 452, 136))
        self.label.setPixmap(QtGui.QPixmap('ui/logo-1.png'))
        #BASE_DIR, 'ui_files/login.ui
        
        self.label.setScaledContents(True)

        usermenue.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=usermenue)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 469, 21))
        usermenue.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=usermenue)
        usermenue.setStatusBar(self.statusbar)

        self.retranslateUi(usermenue)
        QtCore.QMetaObject.connectSlotsByName(usermenue)

        # connect buttons to their respective actions
        self.pushButton_4.clicked.connect(self.Applications_action)
        self.pushButton_5.clicked.connect(self.Main_Menue_action)
        self.pushButton_2.clicked.connect(self.Interviews_action)
        self.pushButton.clicked.connect(self.Mentor_Meeting_action)
        self.pushButton_6.clicked.connect(self.exit_app)

    def retranslateUi(self, usermenue):
        _translate = QtCore.QCoreApplication.translate
        usermenue.setWindowTitle(_translate("usermenue", "User Menue"))
        self.pushButton_4.setText(_translate("usermenue", "Applications"))
        self.pushButton_5.setText(_translate("usermenue", "Main Menu"))
        self.pushButton_6.setText(_translate("usermenue", "Exit"))
        self.pushButton_2.setText(_translate("usermenue", "Interviews"))
        self.pushButton.setText(_translate("usermenue", "Mentor Meeting"))

    # 👇 Function 
    def Applications_action(self):
        self.main_window = QtWidgets.QMainWindow()
        self.application = Ui_applications()
        self.application.setupUi(self.main_window)

        if self.application.tableWidget is None:
          print("Table widget is not initialized.")
        else:
           print("Table widget is initialized.")
           self.application.tableWidget.setColumnCount(0)
           self.application.tableWidget.setRowCount(0)
        set_table_data(self.application, "Applications.xlsx")

        self.main_window.show()

    def Main_Menue_action(self):
        from login import new_login  # Move import here
        self.user_window = QtWidgets.QMainWindow()
        self.user_ui = new_login()
        self.user_ui.setupUi(self.user_window)
        self.user_window.show()

    def Interviews_action(self):
        self.main_window = QtWidgets.QMainWindow()
        self.application = Ui_Interviews()
        self.application.setupUi(self.main_window)

        if self.application.tableWidget is None:
          print("Table widget is not initialized.")
        else:
           print("Table widget is initialized.")
           self.application.tableWidget.setColumnCount(0)
           self.application.tableWidget.setRowCount(0)
        set_table_data(self.application, "Interviews.xlsx")

        self.main_window.show()

    def Mentor_Meeting_action(self):
        print("🔘 open Mentor Meeting")
  
        self.mentor_ui = Ui_MentorMenue()
        self.main_window = QtWidgets.QMainWindow()
        self.application = Ui_MentorMenue()
        self.application.setupUi(self.main_window)

        if self.application.tableWidget is None:
          print("Table widget is not initialized.")
        else:
           print("Table widget is initialized.")
           self.application.tableWidget.setColumnCount(0)
           self.application.tableWidget.setRowCount(0)
        set_table_data(self.application, "Mentors.xlsx")

        self.main_window.show()
   

    def exit_app(self):
        print("🛑exit ")
        QtWidgets.QApplication.quit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    usermenue = QtWidgets.QMainWindow()
    ui = Ui_usermenue()
    ui.setupUi(usermenue)
    usermenue.show()
    sys.exit(app.exec())
